name: Evalite
version: '${version}'
main: dev.reassembly.evalite.Evalite
api-version: '1.21'
authors:
  - Reassembly
description: The Free and Open-Source core for your paper network
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.19.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.19.0